# Generated by Django 5.0.3 on 2024-03-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_remove_tweet_nickname_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='username',
        ),
    ]
